<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="skin/css/ZJPcustomerservice.css" rel="stylesheet" type="text/css" />
<title>客服服务</title>
</head>
<div id="menu_panel">

<div id="menu_section">
   <ul class="navi">
   	 <li><a href="http://t.sina.com.cn/zengsn" class="hover">曾少宁老师</a></li>
     <li><a href="http://t.sina.com.cn/1775421363">周永丰</a></li>
      <li><a href="http://t.sina.com.cn/lizhaoyi19890903">李招意</a></li>
     <li><a href="http://t.sina.com.cn/2013624157">张健平</a></li>
      <li><a href="">杨海亮</a></li>
     <li><a href="http://t.sina.com.cn/1728416901">卢伟灵</a></li>
     <li><a href="http://t.sina.com.cn/summerdir">叶茂安</a></li>
    <li><a href="http://home.cnblogs.com/u/naijsp/">庄秋乃</a></li>
    <li><a href="http://t.sina.com.cn/2082938781">叶景</a></li>
  </ul>
  </div>
  </div>
  <div id="allen1">
  <table width="938" height="184">
    <tr>
       <td height="106"><a href="http://t.sina.com.cn/zengsn" class="tooltip" title="曾少宁老师"><img src="skin/image/ZJP01.jpg"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/1775421363" class="tooltip" title="周永丰同学"><img src="skin/image/ZJP02.jpg"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/lizhaoyi19890903" class="tooltip" title="李招意同学"><img src="skin/image/ZJP03.png"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/2013624157" class="tooltip" title="张健平同学"><img src="skin/image/ZJP04.jpg"  width="91" height="91"/></a></td>
       <td><a href="" class="tooltip" title="杨海亮同学"><img src="skin/image/ZJP05.jpg"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/1728416901" class="tooltip" title="卢伟灵同学"><img src="skin/image/ZJP06.jpg"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/summerdir" class="tooltip" title="叶茂安同学"><img src="skin/image/ZJP07.png"  width="91" height="91"/></a></td>
       <td><a href="http://home.cnblogs.com/u/naijsp/" class="tooltip" title="庄秋乃同学"><img src="skin/image/ZJP08.jpg"  width="91" height="91"/></a></td>
       <td><a href="http://t.sina.com.cn/2082938781" class="tooltip" title="叶景同学"><img src="skin/image/ZJP09.jpg"    width="91" height="91"/></a></td>
     </tr>
   </table>
  </div>
  <div id="allen2">
 <!-- begin :客户服务 -->
<DIV id=divStay style="POSITION: center"> 
<TABLE cellSpacing=0 cellPadding=0  border=0> 
<TBODY> 
<TR> 
<TD vAlign=top width="10%">¡¡</TD></TR></TBODY></TABLE></DIV> 
<SCRIPT language=javascript> 
function picsize(obj,MaxWidth){ 
img=new Image(); 
img.src=obj.src; 
if (img.width>MaxWidth) 
{ 
return MaxWidth; 
} 
else 
{ 
return img.width; 
} 
} 
function CloseQQ() 
{ 
divStayTopleft.style.display="none"; 
return true; 
} 
var online= new Array(); 
</SCRIPT> 
<div id="divStayTopleft" style="POSITION: center"> 
<table cellspacing="0" cellpadding="0" width="109" border="0"> 
<tr> 
<td colspan="3"> 
<a onClick="CloseQQ()" href="javascript:;" shape="circle" coords="91,16,12"> 
<img height="34" src="http://js.alixixi.com/texiaotu/qq_top.gif" width="109" usemap="#Map" border="0"></a></td> 
</tr> 
<tr> 
<td width="6"><img height="100" src="http://js.alixixi.com/texiaotu/qq_life.gif" width="6"></td> 
<td valign="top" width="96" background="sto/qq_bg.gif"> 
<table cellspacing="0" cellpadding="0" width="90" align="center" border="0"> 
<tr> 
<td height="30"> 
<table cellspacing="0" cellpadding="0" width="90" border="0"> 
<tr> 
<td> 
<img height="13" src="http://js.alixixi.com/texiaotu/qq_ico1.gif" width="16"><span class="font_12"> 
<span style="font-size: 9pt">航程网</span></span></td> 
</tr> 
</table> 
</td> 
</tr> 
<tr> 
<td> 
<table border="0" width="100%" cellpadding="2" id="table47"> 
<tr> 
<td width="15" valign="top" height="23"> 
<img border="0" src="http://js.alixixi.com/texiaotu/qq_v01.gif" width="16" height="16"></td> 
<td valign="bottom"><script>document.write("<a target=blank href=tencent://message/?uin=1038295900&Site=航程网&Menu=yes><img border=0 SRC=http://wpa.qq.com/pa?p=1:1038295900:10 alt=[航程网]></a>");</script></td> 
</tr> 
</table> 
</td> 
</tr> 
<tr> 
<td></td> 
</tr> 
<tr> 
<td> 
<table border="0" width="100%" cellpadding="2" id="table47"> 
<tr> 
<td width="15" valign="top" height="23"> 
<img border="0" src="http://js.alixixi.com/texiaotu/qq_n01.gif" width="16" height="16"></td> 
<td valign="bottom"><script>document.write("<a target=blank href=tencent://message/?uin=839697835&Site=航程网&Menu=yes><img border=0 SRC=http://wpa.qq.com/pa?p=1:839697835:10 alt=[航程网]></a>");</script></td> 
</tr> 
</table> 
</td> 
</tr> 
<tr> 
<td></td> 
</tr> 
</table> 
</td> 
<td width="7"><img height="100" src="http://js.alixixi.com/texiaotu/qq_right.gif" width="7"></td> 
</tr> 
<tr> 
<td colspan="3"> 
<img height="30" src="http://js.alixixi.com/texiaotu/qq_bottom1.gif" width="109"></td> 
</tr> 
<tr> 
<td colspan="3"> 
<img height="33" src="http://js.alixixi.com/texiaotu/qq_logo.gif" width="109"></td> 
</tr> 
</table> 
</div> 
<script type="text/javascript"> 
function FloatTop() 
{ 
var startX1 =document.body.offsetWidth-125 ,startY1 = 5; 
var startX2 =0,startY2 = 95; 
var ns = (navigator.appName.indexOf("Netscape") != -1); 
var d = document; 
function ml(id,startX,startY) 
{ 
var el=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id]; 
if(d.layers)el.style=el; 
el.sP=function(x,y){this.style.left=x;this.style.top=y;}; 
el.x = startX; 
el.y = startY; 
return el; 
} 
window.stayTopLeft=function() 
{ 
var pY = ns ? pageYOffset : document.body.scrollTop; 
ftlObj.y += (pY + startY1 - ftlObj.y)/8; 
ftlObj1.y += (pY + startY2 - ftlObj1.y)/8; 
ftlObj.sP(document.body.scrollLeft+document.body.offsetWidth-125, ftlObj.y); 
ftlObj1.sP(ftlObj1.x, ftlObj1.y); 
setTimeout("stayTopLeft()", 30); 
} 
ftlObj = ml("divStay",(document.body.scrollLeft+document.body.offsetWidth)/100,0); 
ftlObj1 = ml("divStayTopLeft",(document.body.scrollLeft+document.body.offsetWidth)/100,0); 
stayTopLeft(); 
} 
FloatTop(); 
</script> 
<!--End:客户服务 --> 
  </div>
  </html>