<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>customerservice</title>
<link href="<?php
echo $this->baseUrl() . '/skin/css/ZJPcustomerservice.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<script language="javascript" type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js'?>"></script>
<script type="text/javascript" 
	src="<?php	echo $this->baseUrl() . '/skin/js/ZJPcustomerservice1.js'; ?>">
</script>
<!-- QQtart -->
<div id="QQFloat" style="Z-INDEX:20;LEFT:0px;VISIBILITY:visible;WIDTH:66px;POSITION:absolute;TOP:150px;HEIGHT:150px;">
	<table cellSpacing="0" cellPadding="0" width="65px" border="0" id="qqtab">
	<tr id="qqstab">
	<td valign="middle" align="center" height="84px"><table border="0" width="65px" cellSpacing="0" cellPadding="0">
	<tr>
	<td width="65px" align="right" valign="middle"><table border="0" cellpadding="0" cellspacing="0" width="65px" style="border:#dee7a8 1px solid">
	<tr>
	<td height="27px" bgcolor="#e20002" style="color:#FFFFFF; font-size:12px; font-weight:bold" align="center">QQ服务</td>
	</tr>
	<tr>
	<td bgcolor="#FFFFFF" height="18px" align="center" style="padding-top:10px; padding-bottom:5px">
	
	
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=1038295900&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1038295900:47" alt="48小时在线咨询" title="48小时在线咨询"></a>
	</td>
	</tr>
	<tr>
	<td align="center" bgcolor="#FFFFFF" style="padding-bottom:5px">
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=965141813&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:965141813:47" alt="48小时在线咨询" title="48小时在线咨询"></a>
	</td>
	</tr>
	<tr>
	<td align="center" bgcolor="#FFFFFF" style="padding-bottom:5px">
	<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=839697835
	&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:839697835
	:47" alt="48小时在线咨询" title="48小时在线咨询"></a>
	</td>
	</tr>
	</table></td>
	</tr>
	</table></td>
	</tr>
	</table>
	</div><script type="text/javascript">
	//<![CDATA[
	var tips; var theTop = 90/*这是默认高度,越大越往下*/; var old = theTop;
	function initFloatTips() {
	tips = document.getElementById('QQFloat');
	moveTips();
	};
	function moveTips() {
	var tt=50;
	if (window.innerHeight) {
	pos = window.pageYOffset
	}
	else if (document.documentElement && document.documentElement.scrollTop) {
	pos = document.documentElement.scrollTop
	}
	else if (document.body) {
	pos = document.body.scrollTop;
	}
	
	pos=pos-tips.offsetTop+theTop;
	pos=tips.offsetTop+pos/10;
	
	if (pos < theTop) pos = theTop;
	if (pos != old) {
	tips.style.top = pos+"px";
	tt=10;
	//alert(tips.style.top);
	}
	old = pos;
	setTimeout(moveTips,tt);
	}
	function close1() {
	abc = document.getElementById('QQFloat');
	abc.style.display='none';
	};
	//!]]>
	initFloatTips();
	</script>
	<!-- QQend -->
</head>
<body>

<div class="ee" style="float:left;width:10%;">
<div id="navigation-block" > 
  <ul id="sliding-navigation">
    <li class="sliding-element">
      <h3>微博客服</h3>
    </li>
    <li class="sliding-element"><a href="#" >曾少宁老师</a></li>
    <li class="sliding-element"><a href="#" >周永丰同学</a></li>
    <li class="sliding-element"><a href="#" >李招意同学</a></li>
    <li class="sliding-element"><a href="#" >张健平同学</a></li>
    <li class="sliding-element"><a href="#" >杨海亮同学</a></li>
    <li class="sliding-element"><a href="#" >卢伟灵同学</a></li>
    <li class="sliding-element"><a href="#" >叶茂安同学</a></li>
    <li class="sliding-element"><a href="#" >庄秋乃同学</a></li>
    <li class="sliding-element"><a href="#" >叶景同学</a></li>
  </ul>
</div>
</div>
<script type="text/javascript">
$(".ee a").live("click", function(){
	if($(this).text()=="曾少宁老师")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/zengsn";
	else if($(this).text()=="周永丰同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/1775421363";
	else if($(this).text()=="李招意同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/lizhaoyi19890903";
	else if($(this).text()=="张健平同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/2013624157";
	else if($(this).text()=="杨海亮同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/2013624157";
	else if($(this).text()=="卢伟灵同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/1728416901";
	else if($(this).text()=="叶茂安同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/summerdir";
	else if($(this).text()=="庄秋乃同学")
		$("#c-c-iframe").get(0).src="http://home.cnblogs.com/u/naijsp/";
	else if($(this).text()=="叶景同学")
		$("#c-c-iframe").get(0).src="http://t.sina.com.cn/2082938781";
		
});
</script>
<!-- 右面板 start -->
<div>
<div class="right">
<div class="left-top-corner">
<div class="right-top-corner">
<div class="border-top"></div>
</div>
</div>
<div class="border-left">
<div class="border-right">
<div class="inner"><iframe  src="http://t.sina.com.cn/zengsn"
	style="width: 100%; height: 800px; border: none;" id="c-c-iframe"> </iframe>
</div>

</div>
</div>
<div class="left-bot-corner">
<div class="right-bot-corner">
<div class="border-bot"></div>
</div>
</div>
</div>
</div>

<!-- 右面板 end -->
</body>
</html>