<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>最新通告</title>
<style type="text/css">
#announce {
	color: red;
	font-size: 20px;
}
</style>
</head>

<body>

<div class="left">
<div class="reme"><marquee>
<?php
	if($this->fliCancleInfo==NULL){
		echo "最近暂时没有航班动态消息";
	}else{
	
		foreach ($this->fliCancleInfo as $key => $value) {
    ?>
	  <div>从<font color="red"><?php
    echo $value['fli_baddress']?></font>到<font
	color="red"><?php
    echo $value['fli_aaddress']?></font> 的<font
	color="red"><?php
    echo $value['fli_no']?></font>航班已取消！</div>
         <?php }
}
?><!--
         <div> 此处可以添加需要通告的信息</div>
         --></marquee></div>
</div>

</body>
</html>

