<!-- index页面css -->
<link href="<?php
echo $this->baseUrl() . '/skin/css/YHLindex.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<!-- 链接jquery -->
<script language="javascript" type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js'?>"></script>
<script type="text/javascript">
$(document).ready(function(){
	$("#frame1").get(0).src="http://php.weather.sina.com.cn/widget/weather.php";
	$("#frame2").get(0).src="<?php
echo $this->baseUrl() . '/Index/dirgramshow'?>";
});
</script>
<div id="main">
<div class="main_left">
<div class="main_top" style="width:40%;">
<table cellspacing="0" cellpadding="0">
	<tr>
		<th>用户登录</th>
	</tr>
	<tr>
		<td><iframe frameborder="0"
			src="<?php echo $this->baseUrl() . '/Customer/login'?>" scrolling="no" width=100% height=170px></iframe></td>

	</tr>
</table>
</div>
<div class="main_top" style="width:59%;">
<table cellspacing="0" cellpadding="0">
	<tr>
		<th>评论</th>
	</tr>
	<tr>
		<td><iframe frameborder="0"
			src="<?php
echo $this->baseUrl() . '/Index/announce-show'?>"
			scrolling="no" width=100% height=170px></iframe></td>
	</tr>
</table>
</div>

<div class="main_bottom">
<table cellspacing="0" cellpadding="0">
	<tr>
		<th class="thoffer">航班优惠</th>
	</tr>
	<tr>
		<td><iframe frameborder="0"
			src="<?php
echo $this->baseUrl() . '/Index/fli-preference'?>"
			scrolling="no" width=100% height=170px></iframe></td>

	</tr>
</table>
</div>
</div>
<div class="main_right">
<table cellspacing="0" cellpadding="0">
	<tr>
		<th class="thweather">最近天气</th>
	</tr>
	<tr>
		<td><iframe frameborder="0" id="frame1" scrolling="no" width="100%"
			height="405px"> </iframe></td>
	</tr>
</table>
</div>
<div class="main_draw">
<table cellspacing="0" cellpadding="0">
	<tr>
		<th class="thdraw">近日销售量</th>
	</tr>
	<tr>
		<td style="height: 300px"><iframe frameborder="0" id="frame2"
			scrolling="no" width=100% height=100%></iframe></td>

	</tr>
</table>
</div>
</div>




