<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
 th{
 	font-size:12px;
 	align:center;
 	color:blue;
 	width:150px;
}
 td{
	font-size:12px;
	align:center;
}
a{
	text-decoration:none;
}
a:hover{
	color:red;
}


a {
    color: #c75f3e;
}



caption {
    padding: 0 0 5px 0;
    width: 700px;     
    font: italic 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
    text-align: right;
}

th {
    font: bold 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
    color: #4f6b72;
    border-right: 1px solid #C1DAD7;
    border-bottom: 1px solid #C1DAD7;
    border-top: 1px solid #C1DAD7;
    letter-spacing: 2px;
    text-transform: uppercase;
    text-align: left;
    padding: 6px 6px 6px 12px;
    background: #CAE8EA url(images/bg_header.jpg) no-repeat;
}

th.nobg {
    border-top: 0;
    border-left: 0;
    border-right: 1px solid #C1DAD7;
    background: none;
}

td {
    border-right: 1px solid #C1DAD7;
    border-bottom: 1px solid #C1DAD7;
    background: #fff;
    font-size:11px;
    padding: 6px 6px 6px 12px;
    color: #4f6b72;
}


td.alt {
    background: #F5FAFA;
    color: #797268;
}



/*---------for IE 5.x bug*/
html>body td{ font-size:11px;} 
</style>

<script type="text/javascript" src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js';?>">
</script>




  <?php 
  		if($this->flightcompanyshow==NULL){
  			echo "输入为空,本网站无法定位到您要查询的信息!";
  		}else{?>
  		<form name="form" 
	  action="<?php echo $this->url(array('controller'=>'Flightcompany','action'=>'flightcomanyshow'));?>" 
	  method="post">
<table border="1" cellspacing="0" cellpadding="2px" bgcolor="#abedef"  align="center" " width="700px">
  <tr> 
   <th scope="col" abbr="Configurations" class="nobg">航空公司代码</th>
   <th scope="col" abbr="Dual 1.8">航空公司名称</th>
  <th scope="col" abbr="Dual 2">航空公司地址</th>
  
   
  </tr>
  <?php 
  		foreach($this->flightcompanyshow as $key=>$value){
  ?>
  <tr>
  	<td align="center" id="flightcompany" scope="row" abbr="G5 Processor" class="specalt">
 	<?php echo $value['com_code'] ?>
  	</td>
  	 <td align="center" class="alt" >
  		<?php echo $value['com_name'] ?>
  	</td>
 	 <td align="center" class="alt" >
  		<?php echo $value['com_address'] ?>
  	</td>
  	 
  	  </tr>
  <?php }}?>
</table>
<center>航空公司简介：</center><br>
<textarea name="t1" cols="72" rows="8"> <?php echo $value['com_information'] ?></textarea>

 
</form>