<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
 th{
 	font-size:12px;
 	align:center;
 	color:blue;
 	width:150px;
}
 td{
	font-size:12px;
	align:center;
}
a{
	text-decoration:none;
}
a:hover{
	color:red;
}
</style>

<script type="text/javascript" src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js';?>">
</script>




  <?php 
  		if($this->flightcompanyshow==NULL){
  			echo "输入为空,本网站无法定位到您要查询的信息!";
  		}else{?>
  		<form name="form" 
	  action="<?php echo $this->url(array('controller'=>'Flightcompany','action'=>'flightcomanyshow'));?>" 
	  method="post">
<table border="1" cellspacing="0" cellpadding="2px" bgcolor="#abedef" align="center" width="700px">
  <tr> 
   <th>航空公司代码</th>
   <th>航空公司名称</th>
   <th>航空公司地址</th>
   <th>航空公司简介</th>
   
  </tr>
  <?php 
  		foreach($this->flightcompanyshow as $key=>$value){
  ?>
  <tr>
  	<td align="center" id="flightcompany">
 	<?php echo $value['com_code'] ?>
  	</td>
  	 <td align="center">
  		<?php echo $value['com_name'] ?>
  	</td>
 	 <td align="center">
  		<?php echo $value['com_address'] ?>
  	</td>
  	 <td align="center">
  		<?php echo $value['com_information'] ?>
  	</td>
  	 
  	
  </tr>
  <?php }}?>
</table>
</form>