
<!-- hotelinformation页面css -->
<link
	href="<?php
echo $this->baseUrl() . '/skin/css/YJhotelinformation.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<!-- 链接页面js -->
<script type="text/javascript"
src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js';?>">
</script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl() . '/skin/js/ZQNflightinformation.js';
?>"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<title>航空公司信息</title>
<div id="scroller">
	<div id="images">
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn3.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn2.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn6.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn4.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn1.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn5.jpg'?>" width=150px height=150px></a>
	</div>
</div>

<!-- 左面板 start -->
<div class="left">
	<div class="subdiv">
		<p class="top">&nbsp;</p>
			<h2>航空公司搜索</h2>
				<div class="search"><br>
					<form name="search" method="post" id="f">
						<label><font size="3px">航空公司名称</font></label>
						<input name="com_name" id="com_name" type="text" size="10"><br>
							<input type="button"  id="search" value="　搜索　" onclick="b()" />
					
					</form>
				
					<p class="bot"></p>
				</div>
		</div>
</div>


<!-- 左面板 end -->
<!--// 右面板 start -->
<div class="right">
<div class="left-top-corner">
<div class="right-top-corner">
<div class="border-top"></div>
</div>
</div>
<div class="border-left">
<div class="border-right">
<div class="inner">
	<div id="hello"><!--
	  <iframe style="width: 100%; height: 220px; border: none;" id="c-c-iframe"
	></iframe> 
	--></div><!--
	 <div class="hoteldetail">	
	<iframe style="width: 100%; height: 220px; border: none;" id="c-c-iframe1" >
	</iframe>
	</div>
	
--></div>

</div>
</div>
<div class="left-bot-corner">
<div class="right-bot-corner">
<div class="border-bot"></div>
</div>
</div>
</div>

<!-- 右面板 end -->