
<!-- hotelinformation页面css -->
<link
	href="<?php
echo $this->baseUrl() . '/skin/css/YJhotelinformation.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<!-- 链接页面js -->
<script type="text/javascript"
src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js';?>">
</script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl() . '/skin/js/ZQNflightinformation.js';
?>"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<title>航空公司信息</title>
<div id="scroller">
	<div id="images">
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn3.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn2.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn6.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn4.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn1.jpg'?>" width=150px height=150px></a>
		<a href="#"><img src="<?php echo $this->baseUrl() . '/skin/image/zqn5.jpg'?>" width=150px height=150px></a>
	</div>
</div>

<!-- 左面板 start -->
<div class="left">
	<div class="subdiv">
		<p class="top">&nbsp;</p>
			<h2>航空公司搜索</h2>
				<div class="search"><br>
					<form name="search" method="post" id="f">
						<label><font size="3px">航空公司名称</font></label>
						<input name="com_name" id="com_name" type="text" size="10"><br>
							<input type="button"  id="search" value="　搜索　" onclick="b()" />
					
					</form>
				
					<p class="bot"></p>
				</div>
		</div>
</div>


<!-- 左面板 end -->
<!--// 右面板 start -->
<div class="right">
<div class="left-top-corner">
<div class="right-top-corner">
<div class="border-top"></div>

</div>
</div>
<div class="border-left">
<div class="border-right">
<div class="inner">
	<div id="hello"><!--
	  <iframe style="width: 100%; height: 220px; border: none;" id="c-c-iframe"
	></iframe> 
	--></div><!--
	 <div class="hoteldetail">	
	<iframe style="width: 100%; height: 220px; border: none;" id="c-c-iframe1" >
	</iframe>
	</div>
	
-->
航空公司相关信息：
<br>
　　特价航线：
<br>
上海－北京，广州，深圳，成都，重庆，西安，三亚，海口，沈阳，哈尔滨，乌鲁木齐，昆明，青岛，南昌，大连，桂林，长沙，长春，福州，延吉，呼和浩特，武汉，厦门，石家庄，郑州，包头，贵阳，绵阳，济南，晋江，兰州，丽江，延吉，南宁，齐齐哈尔，汕头
<br>
<br>

　　影响机票价格的因素?
<br>
　　机票价格主要是由航空公司内部按市场经济规律统一调控价格，需求量大的时候价格上涨，需求量小的时候价格下调，另外是航线因素，不同的航线打折的幅度可能会大相径庭，通常班次比较多的航线打折的幅度会大一些，其次是季节因素，不同的季节机票价格差异较大，比如春节期间各航线的价格都比较高，故机票价格主要是航空公司在调控，作为机票代理商我们可以向航空公司申请低某些航线的低价票，或者是是按排团队票等等，尽量为客户提供低廉的机票　　
<br>
<br>
　　如何才能订到打折机票?
<br>

　首先，您要确定您的航程，以及您出行的大致时间，当然，时间越宽裕的话，选择性就越大，最好能确定在一个范围，一般是一个星期以内就可以，这样价格比较低，而且订票员也方便给您查询。接下来就是订票的时间，是越早越好吗？当然不是，不同的航线有不同的最佳订票时间。一般请况下,如果你订本月的机票的话，月初就可以订到本月最优惠的价格了。有一些比较热门的城市,比如到广州深圳北京这几个城市的机票像，因为航空公司还没有放低折扣的仓位。另个还有一些航线只有提前3-5天的时候航空公司才会放低折扣的机票，这就只能咨询代理商才能知道。还有一些跟团的机票，一般都是提前预定，但是提前1-2天才能出票。如果您是订下月的机票的话，最好是在本月底或者是下月初再订，这样才能订到最低折扣的机票。
 <br><font color = green>温馨提示：你可以在左端输入你想查询的航空公司信息 </font>
</div>

</div>
</div>
<div class="left-bot-corner">
<div class="right-bot-corner">
<div class="border-bot"></div>
</div>
</div>
</div>

<!-- 右面板 end -->