<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>会员订单</title>
<link
	href="<?php
echo $this->baseUrl() . '/skin/css/ZYFtablecloth.css'?>"
	media="screen" rel="stylesheet" type="text/css" />

<!-- 链接页面js -->
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/js/ZYFtablecloth.js'?>"></script>

<!-- 加载jquery -->
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>

<!-- 页面浮动层 -->
<link href="<?php
echo $this->baseUrl() . '/skin/css/ZYFcommon.css'?>"
	media="screen" rel="stylesheet" type="text/css" />

<link
	href="<?php
echo $this->baseUrl() . '/skin/css/ZYFpowerFloat.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/js/ZYFjquery-powerFloat-min.js'?>"></script>
</head>
<body>
<center>

<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="10%">航班号</th>
		<th>起始点</th>
		<th>抵达点</th>
		<th>舱位</th>
		<th>价格</th>
		<th>订票时间</th>
		<th>操作1</th>
	</tr>
	<?php
foreach ($this->flightinformation as $key => $value) {
    ?>
	<tr>
		<td><?php echo $value['com_code'].$value['boo_no']?></td>
		<td><?php echo $value['boo_baddress']?></td>
		<td><?php echo $value['boo_aaddress']?></td>
		<td><?php echo $value['boo_berth']?></td>
		<td><?php echo $value['boo_fare']?>元</td>
		<td><?php echo $value['boo_time']?></td>
		<td><a href="javascript:;"
			rel="<?php
    echo 'targetBox' . $this->i;
    ?>">详情</a></td>
	</tr>
	<div id="<?php
    echo 'targetBox' . $this->i;
    ?>"
		class="shadow target_box dn">
	<div class="target_list">
	时间：<?php echo $value['boo_btime'].'-'.$value['boo_atime']?>
	</div>
	<div class="target_list">
	座位号：<?php 
	echo $value['boo_no'];
	if($value['flag_pay']=="1") 
	echo "(已付款)"; 
	else
	echo "(未付款)";
	?></div>
	<div class="target_list">
	是否退票：<?php 
	if($value['flag_pass']=="1") 
	echo "否"; 
	else
	echo "<font color=red>是</font>";
	?>
	</div>
	</div>
	<?php
    $this->i += 1;
}
?>	
</table>
<!-- 页面样式
All：显示所有页；

Elastic：Google式，页码范围会根据用户当前页而扩展或缩小；

Jumping：页码最后页之后会显示第一页；

Sliding：Yahoo式，当前页会放在页码中间，这是默认样式。 
 -->
<?php
echo $this->paginationControl($this->flightinformation, 'Sliding', 
'/customer/pagelist.phtml');
?>
</center>


<script type="text/javascript">
$(function() {
		$("a").powerFloat();
})
</script>

</body>
</html>