<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>register</title>
<body>
<center>
<form name="login"
	action="<?php
echo $this->url(array('controller' => 'customer', 'action' => 'register'));
?>"
	method="post">

<table width="39%" height="105" border="0">
	<tr>

		<td width="27%" height="30">账户：</td>

		<td width="73%" height="30"><input name="cus_account" type="text"
			id="cus_account"></td>
	</tr>
	<tr>
		<td height="30">密码：</td>

		<td height="30"><input name="cus_pwd" type="password" id="cus_pwd"></td>
	</tr>
	<tr>
		<td height="30">确定密码：</td>

		<td height="30"><input name="cus_pwd2" type="password" id="cus_pwd2">

		</td>
	</tr>
	<tr>
		<td height="30">性别：</td>

		<td height="30"><input name="cus_sex" type="password" id="cus_sex"></td>
	</tr>

	<tr>
		<td height="30">身份证号：</td>

		<td height="30"><input name="cus_id" type="text" id="cus_id"></td>
	</tr>
	<tr>

		<td height="30">联系电话</td>
		<td height="30"><input name="cus_telnumber" type="text"
			id="cus_telnumber"></td>

	</tr>
	<tr>
		<td height="30">Mail：</td>

		<td height="30"><input name="cus_email" type="text" id="cus_email"></td>
	</tr>
	<tr>

		<td height="30">注册日期</td>

		<td height="30"><input name="cus_time" type="text" id="cus_time"></td>
	</tr>


	<tr>
		<td><input type="submit" value="　注册　" /></td>
		<td><input type="button" value="　重置　" /></td>
	</tr>


</table>

</form>
</center>
</body>
</html>
