<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<head>
<title>register</title>
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>

<script type="text/javascript">
$(document).ready(function(){
	
	
	
	$('form :input').blur(function(){
		var $parent = $(this).parent();
		$parent.find(".formtips").remove();
		//验证账户
		if($(this).is('#cus_account')){
			if(this.value == "" || this.value.length< 3){
				var errorMsg ="<font color=red>*请填写正确的帐号名<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
		}
		//验证身份证
		if($(this).is('#cus_id')){
			if(this.value == "" || this.value.length<18){
				var errorMsg ="<font color=red>*请输入正确的18位身份证号码<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
		}
		//验证密码
		if($(this).is('#cus_pwd')){
			if(this.value == "" || this.value.length< 8){
				var errorMsg ="<font color=red>*密码最短不能小于6位<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入符合格式<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
			
		}
}  ) ;

		}) ;

</script>
</head>


<body>
认真填写以下信息，以便找回用户名/密码
<hr width="100% size="1">

<form name="login"
	action="<?php
echo $this->url(array('controller' => 'customer', 'action' => 'customerpwd'));
?>"
	method="post">

<table width="90%" height="105" border="0">

<tr>
		<td width="10%" height="30">账户名：</td>

		<td width="73%" height="30"><input name="cus_account" type="text"
			id="cus_account" maxlength="12"> </td>
			</tr>
			<tr>
		<td width="10%" height="30">身份证：</td>

		<td width="73%" height="30"><input name="cus_id" type="text"
			id="cus_id" maxlength="18"> </td>
			</tr>
			<tr>
		<td width="10%" height="30">密码：</td>

		<td width="73%" height="30"><input name="cus_pwd" type="text"
			id="cus_pwd" maxlength="14"> </td>
			</tr>

<tr>
<td><input type="submit" value="　下一步　" id="next" />
</td>
</tr>


</table>
</form>

<hr width="100%" size="1">


</body>
</html>