<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<title>register</title>
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>
<script type="text/javascript">
$(document).ready(function(){
	
	//重置操作
	$("#cz").click(
			function(){
				alert ("你可以重新填写了");
				
			}
			);
	
	
	$('form :input').blur(function(){
		var $parent = $(this).parent();
		$parent.find(".formtips").remove();
		//验证账户
		if($(this).is('#cus_account')){
			if(this.value == "" || this.value.length <3){
				var errorMsg ="<font color=red>*账户名最短不能小于三位<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
		}
		//验证密码
		if($(this).is('#cus_pwd')){
			if(this.value == "" || this.value.length< 8){
				var errorMsg ="<font color=red>*密码最短不能小于6位<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入符合格式<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
			
		}
		//验证确认密码
		if($(this).is('#cus_pwd2')){
			if($(this).val()  == $("#cus_pwd").val() &&  this.value !=  "" ){
				var errorMsg ="<font color=green>下一步<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=red>*请确认两次输入一致且不为空<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
		}
		//验证身份证
		if($(this).is('#cus_id')){
			if(this.value == "" || this.value.length<18){
				var errorMsg ="<font color=red>*请输入正确的18位身份证号码<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
		}
		//验证邮箱
		if($(this).is('#cus_email')){
			if(this.value == "" || (this.value !=  "" && !/.+@.+\.[a-zA-Z]{2,4}$/.test(this.value))){
				 var errorMsg ="<font color=red>*请输入正确的email地址<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>"; 
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
			}
		//验证电话号
		if($(this).is('#cus_telnumber')){
			
			if(this.value == "" || this.value.length <  11 || ! (/^1[358]\d{9}$/.test(this.value)) ) {
				var errorMsg ="<font color=red>*请输入正确的11位电话号码<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');}
			else { var okMsg = "<font color=green>输入正确<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
			
			}
}  ) ;

		}) ;

</script>
</head>


<body>
填写完完整注册信息后方能注册
<hr width="100%" size="1">

<form name="login"
	action="<?php
echo $this->url(array('controller' => 'customer', 'action' => 'customerregister'));
?>"
	method="post">

<table width="90%" height="105" border="0">
	<tr>

		<td width="10%" height="30">账户：</td>

		<td width="73%" height="30"><input name="cus_account" type="text"
			id="cus_account" maxlength="12"> </td>

	</tr>
	<tr>
		<td height="30">密码：</td>

		<td height="30"><input name="cus_pwd" type="password" id="cus_pwd"
			maxlength="14"></td>
	</tr>
	<tr>
		<td height="30">确定密码：</td>

		<td height="30"><input name="cus_pwd2" type="password" id="cus_pwd2"
			maxlength="14"></td>
	</tr>

	<tr>
		<td height="30">性别：</td>

		<td height="30"><select name="cus_sex" id="sex">
			<option selected>男</option>
			<option>女</option>

		</select></td>
	</tr>

	<tr>
		<td height="30">身份证号：</td>

		<td height="30"><input name="cus_id" type="text" id="cus_id"
			maxlength="18"></td>
	</tr>
	<tr>

		<td height="30">联系电话</td>
		<td height="30"><input name="cus_telnumber" type="text"
			id="cus_telnumber" maxlength="11" /> </td>

	</tr>
	<tr>
		<td height="30">Mail：</td>

		<td height="30"><input name="cus_email" type="text" id="cus_email"
			maxlength="40"></td>
	</tr>
	

	<tr>
		<td><input type="submit" value="　注册　" id="shiyan" /></td>
		<td><input type="reset" value="　重置　" id="cz" /></td>
	</tr>
</table>



</form>

<hr width="100%" size="1">
请记住以上填写的注册信息，以便下次登录和找回密码!
</body>
</html>