<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<title>commerinformationalter</title>
<script type="text/javascript" src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js'; ?>"></script>
<link href="<?php echo $this->baseUrl() . '/skin/css/YMAregister.css'?>" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript">
	$(document).ready(function(){
		
		$("form :input.required").each(function(){
			var $required = $("<strong class='high'> *</strong>"); 
			$(this).parent().append($required);
		});
		
		//重置操作
		$("#cz").click(function(){
			$(".formtips").remove(); 
		});
	
		//2011/04/30 叶茂安修改
		$('form :input').blur(function(){
			var $parent = $(this).parent();
		
			$parent.find(".formtips").remove();

			//验证原密码
			if($(this).is('#pre_pwd')){
				var pre_pwd=$("#pre_pwd").val();
				$.ajax({
					type:"post",
					url:"/Airline/Customer/checkpwd",
					contentType: "application/x-www-form-urlencoded; charset=utf-8",
					cache: true,
					data:{pre_pwd:pre_pwd},
					success:function(data,textStatus){
						if(data[0].success=="success"){
							var Msg = "<font color=green>信息正确,可以修改</font>";
							$parent.append('<span class="formtips onSuccess">' +Msg +'</span>');
						}else{
							var Msg="<font color=red>原密码错误,请重新输入!</font>";
							$parent.append('<span class="formtips onError">' +Msg +'</span>');
						}
					},
					error: function(data, textStatus) {
					}
				});
			}
			
			//验证密码
			if($(this).is('#cus_pwd')){
				if(this.value == "" || this.value.length< 6){
					var errorMsg ="<font color=red>密码最短不能小于6位<font>";
					$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');
				}else { 
					var okMsg = "<font color=green>输入符合格式<font>";
				$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			}
			//验证确认密码
			//2011/04/30  叶茂安修改
			if($(this).is('#cus_pwd2')){
				if($(this).val()  == $("#cus_pwd").val() &&  this.value !=  "" ){
					var Msg ="<font color=green>密码输入正确</font>";
					$parent.append('<span class = "formtips onSuccess">' + Msg+ '</span>');
				}
				else { 
					var Msg = "<font color=red>请确认两次输入一致且不为空</font>";
					$parent.append('<span class="formtips onError">' +Msg +'</span>');
				}
			
			}
			
			//验证邮箱
			if($(this).is('#cus_email')){
				if(this.value == "" || (this.value !=  "" && !/.+@.+\.[a-zA-Z]{2,4}$/.test(this.value))){
					var errorMsg ="<font color=red>请输入正确的email地址</font>";
					$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');
				}else{
					var okMsg = "<font color=green>输入正确</font>"; 
				$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
			
			}
			//验证电话号
			if($(this).is('#cus_telnumber')){
			
				if(this.value == "" || this.value.length <  11 || ! (/^1[358]\d{9}$/.test(this.value)) ) {
					var errorMsg ="<font color=red>请输入正确的11位电话号码</font>";
					$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');
				}
				else { 
					var okMsg = "<font color=green>输入正确</font>";
					$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
				}
			});

			$("#alter").click(function(){
				var cus_pwd=$("#cus_pwd").val();
				var cus_pwd2=$("#cus_pwd2").val();
				var cus_telnumber=$("#cus_telnumber").val();
				var cus_email=$("#cus_email").val();
				//alert(cus_sex);
				$.ajax({
					type:"post",
					url:"/Airline/Customer/customerinformationalterhandler",
					contentType: "application/x-www-form-urlencoded; charset=utf-8",
					cache: true,
					data:{ cus_pwd:cus_pwd,cus_pwd2:cus_pwd2,cus_telnumber:cus_telnumber,cus_email:cus_email },
					success:function(data,textStatus){
						if(data[0].success=="success"){
							var Msg = "用户信息修改成功!";
						}else{
							//$(".formtips").remove();
							var Msg="修改信息失败,请核对数据!";
						}
						alert(Msg);
					},
					error: function(data, textStatus) {
					}
				});
			});
		}) ;

</script>
</head>


<body>

会员信息修改
<hr width="100%" size="1">
<form name="change"  method="post"  action="<?php echo $this->url(array('controller'=>'customer','action'=>' customerinformationalter'));?>"  >
	<table cellspacing="0" cellpadding="0">
  <?php 
  		foreach($this-> customers  as $key=>$value){
  ?>
			<tr>
				<th width=50>会员编号：</th>
				<td width=200><?php echo $value['cus_autoid'] ?></td>
			</tr>
			<tr>
				<th width=50>会员账号：</th>
				<td width=200><?php echo $value['cus_account'] ?></td>
			</tr>			
			<tr>
				<th width=50>密&nbsp;&nbsp;码：</th>
				<td width=200><?php echo $value['cus_pwd'] ?></td>
			</tr>			
			<tr>
				<th width=50>身份证号：</th>
				<td width=200><?php echo $value['cus_id'] ?></td>
			</tr>	
			<tr>
				<th width=50>性&nbsp;&nbsp;别：</th>
				<td width=200><?php echo $value['cus_sex'] ?></td>
			</tr>	
			<tr>
				<th width=50>电话号码：</th>
				<td width=200><input name="cus_telnumber" type="text" class="required" id="cus_telnumber" maxlength="11" /> </td>
			</tr>	
			<tr>
				<th width=50>电子邮件：</th>
				<td width=200><input name="cus_email" type="text" class="required" id="cus_email" maxlength="30"></td>
			</tr>	
			<tr>
				<th width=50>注册时间：</th>
				<td width=200><?php echo $value['cus_time'] ?></td>
			</tr>	
			<tr>
				<th width='50'>积&nbsp;&nbsp;分：</th>
				<td width=200><?php echo $value['cus_integral'] ?></td>
			</tr>		
				<tr>
			<td><input type="button" value="　修改　" id="alter" /></td>
			<td><input type="reset" value="　重置　" id="cz" /></td>
		</tr>
		  <?php } ?>																																				
		</table>
</form>

<hr width="100%" size="1">

</body>
</html>