<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<title>register</title>
<script type="text/javascript" src="<?php echo $this->baseUrl() . '/skin/source/jquery/jquery.js'; ?>"></script>
<link href="<?php echo $this->baseUrl() . '/skin/css/YMAregister.css'?>" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript">
$(document).ready(function(){
	
	$("form :input.required").each(function(){
		var $required = $("<strong class='high'> *</strong>"); 
		$(this).parent().append($required);
	});
	
	//重置操作
	$("#cz").click(function(){
			$(".formtips").remove(); 
	});

	//2011/04/30 叶茂安修改
	$('form :input').blur(function(){
		var $parent = $(this).parent();
	
		$parent.find(".formtips").remove();
		
		
		//验证新密码
		if($(this).is('#newpwd')){
			if(this.value == "" || this.value.length< 6){
				var errorMsg ="<font color=red>密码最短不能小于6位<font>";
				$parent.append('<span class = "formtips onError">' + errorMsg+ '</span>');
			}else { 
				var okMsg = "<font color=green>输入符合格式<font>";
			$parent.append('<span class="formtips onSuccess">' +okMsg +'</span>');}
		}
		//验证确认密码
		
		if($(this).is('#newpwd2')){
			if($(this).val()  == $("#newpwd").val() &&  this.value !=  "" ){
				var Msg ="<font color=green>密码输入正确</font>";
				$parent.append('<span class = "formtips onSuccess">' + Msg+ '</span>');
			}
			else { 
				var Msg = "<font color=red>请确认两次输入一致且不为空</font>";
				$parent.append('<span class="formtips onError">' +Msg +'</span>');
			}
		
		}
		


		});
	}) ;

</script>
</head>


<body>
修改密码
<hr width="100%" size="1">

<form name="login"  action="<?php echo $this->url(array('controller'=>'customer','action'=>'customeralterpwd'));?>"  method="post" >

<table width="90%" height="105" border="0" align="center">
	
	<tr>
		<td height="30">新密码：</td>

		<td height="30" width="100%">
		<input name="newpwd" type="password" id="newpwd" class="required" maxlength="14"></td>
	</tr>
	<tr>
		<td height="30">确定密码：</td>

		<td height="30" width="100%">
		<input name="newpwd2" type="password" id="newpwd2" class="required" maxlength="14"></td>
	</tr>

	

	
	

	<tr>
		<td><input type="submit" value="　修改　" id="alter" /></td>
		<td><input type="reset" value="　重置　" id="cz" /></td>
	</tr>
</table>



</form>

<hr width="100%" size="1">
请记住你修改的新密码
</body>
</html>