<!-- //编辑者：李招意 -->
<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>登录界面</title>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/skin/source/jquery/jquery.js' ;?>"></script>
<body>
<script type="text/javascript">
	$(document).ready(function(){
		$("#submit").click(function(){
			//var cus_account=$("#cus_account").val();
			//var cus_pwd=$("#cus_pwd").val();
			if ($.trim($("#cus_account")[0].value) == "")
			{
			  alert("会员账号不能为空！");
			} else if ($.trim($("#cus_pwd")[0].value) == "")
			{
				  alert("会员密码不能为空！");
				}
		});

	});	
</script>
<center>
<form name="login" 
	  action="<?php echo $this->url(array('controller'=>'customer','action'=>'customerlogin'));?>" 
	  method="post">
	<!-- 身份证号：<input type="text" name="cus_id" id="cus_id" /><br /> -->
	会员账号：<input type="text" name="cus_account" id="cus_account" /><br />
	会员密码：<input type="text" name="cus_pwd" id="cus_pwd" /><br />
	<input type="submit" id="submit" value="登录" />
	<input type="reset" value="取消" /><br />
	新会员？<a href="<?php echo $this->baseUrl() . '/Customer/customerregister'?>">会员注册</a><br />
	<a href="<?php echo $this->baseUrl() . '/Customer/customermodifypassword'?>">忘记密码</a>
</form>
</center>
</body>
</html>