<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<head>
<title>register</title>
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>

<script type="text/javascript">

$(document).ready(function(){

	
	$("form :input.required").each(function(){
		var $required = $("<strong class='high'> *</strong>"); 
		$(this).parent().append($required);
	});
	
	

	
	$('form :input').blur(function(){
		var $parent = $(this).parent();
	
		$parent.find(".formtips").remove();
		//验证账户
		if($(this).is('#cus_account')){
		
			if(this.value == "" || this.value.length <3){
				var Msg ="<font color=red>账户名最短不能小于三位<font>";
				$parent.append('<span class = "formtips onError">' + Msg+ '</span>');
			}else{
				var account=$("#cus_account").val();
				$.ajax({
					type:"post",
					url:"/Airline/Customer/checkaccount",
					contentType: "application/x-www-form-urlencoded; charset=utf-8",
					cache: true,
					data:{account:account},
					success:function(data,textStatus){
						if(data[0].success=="success"){
							var Msg = "<font color=red>该账户名不存在!</font>";
							$parent.append('<span class="formtips onSuccess">' +Msg +'</span>');
							
						}else{
							var Msg="<font color=green>下一步</font>";
							$parent.append('<span class="formtips onError">' +Msg +'</span>');
						}
						
					},
					error: function(data, textStatus) {
					}
				});
			}
		
		
		}

		if($(this).is('#cus_id')){
			if(this.value == "" || this.value.length<18){
				var Msg ="<font color=red>请输入正确的18位身份证号码</font>";
				$parent.append('<span class = "formtips onError">' + Msg+ '</span>');
			}else{
				var cus_id=$("#cus_id").val();
				$.ajax({
					type:"post",
					url:"/Airline/Customer/checkcusid",
					contentType: "application/x-www-form-urlencoded; charset=utf-8",
					cache: true,
					data:{cus_id:cus_id},
					success:function(data,textStatus){
						if(data[0].success=="failure"){
							var Msg = "<font color=green>身份证数据输入正确</font>";
							$parent.append('<span class="formtips onSuccess">' +Msg +'</span>');
						}else{
							var Msg="<font color=red>身份证信息错误,请重新输入!</font>";
							$parent.append('<span class="formtips onError">' +Msg +'</span>');
						}
						
					},
					error: function(data, textStatus) {
					}
				});
			}
		}
		
		
		
		
		});

		
	} ) ;
	

</script>
</head>


<body>
认真填写以下信息，以便找回密码
<hr width="100%" size="1">

<form name="login"
	action="<?php
echo $this->url(array('controller' => 'customer', 'action' => 'customerpwd'));
?>"
	method="post">
<table width="90%" height="105" border="0" align="center">
	<tr>
	<td width="10%" height="30">账户名：</td>
	<td width="100%" height="30"> <input name="cus_account" type="text"
	id="cus_account" maxlength="12"></td>
	</tr>

<tr>
	<td height="30">身份证：</td>
	<td width="100%" height="30"> <input name="cus_id" type="text"
	id="cus_id" maxlength="18"></td>
	</tr>
<tr>
<td>
<input type="submit" value="　下一步　" id="next" />
</td>
</tr>
</table>

</form>

<hr width="100%" size="1">


</body>
</html>