<!-- 编辑者：李招意 -->
<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<form action="customercomment" method="post">
<div id="commentform">
我要发表评论 <br />
<textarea name="comment_content" cols="65" rows="4"></textarea>
  <p align="left"><!--
  账号：<input type="text" size="12" name="cus_account" id="cus_account" />
  密码：<input type="text" size="12" name="cus_pwd" id="cus_pwd" />
  新会员？<a href="http://localhost/Airline/Customer/register">会员注册</a>
  -->
  <input type="submit" name="sent" value="发表评论" >
  <input type="reset" name="reset" value="取消评论" >
  </p>
</div>
</form>