<!-- //编辑者：李招意 -->
<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>航班查询</title>
<link
	href="<?php
echo $this->baseUrl() . '/skin/css/ZYFtablecloth.css'?>"
	media="screen" rel="stylesheet" type="text/css" />

<!-- 链接页面js -->
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/js/ZYFtablecloth.js'?>"></script>

<!-- 加载jquery -->
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>

<!-- 页面浮动层 -->
<link href="<?php
echo $this->baseUrl() . '/skin/css/ZYFcommon.css'?>"
	media="screen" rel="stylesheet" type="text/css" />

<link
	href="<?php
echo $this->baseUrl() . '/skin/css/ZYFpowerFloat.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/js/ZYFjquery-powerFloat-min.js'?>"></script>
</head>
<body>
您好<?php Zend_Session::start(); 
       $customerNamespace = new Zend_Session_Namespace('customer');
        echo $customerNamespace->cus_account;?>，您的个人信息如下：<br />
<center>
<table cellspacing="0" cellpadding="0">
  <tr>
    <th>会员编号</th>
    <th>会员账号</th>
    <th>密&nbsp;&nbsp;码</th>
    <th>身份证号</th>
    <th>性&nbsp;&nbsp;别</th>
    <th>电话号码</th>
    <th>电子邮件</th>
    <th>注册时间</th>
    <th>积&nbsp;&nbsp;分</th>
  </tr>
  <?php 
  		foreach($this->customers as $key=>$value){
  ?>
  <tr>
  	<td>
 	 <?php echo $value['cus_autoid'] ?>
  	</td>
 	<td>
  		<?php echo $value['cus_account'] ?>
  	</td>
  	  	<td>
 	 <?php echo $value['cus_pwd'] ?>
  	</td>
 	<td>
  		<?php echo $value['cus_id'] ?>
  	</td>
  	  	<td>
 	 <?php echo $value['cus_sex'] ?>
  	</td>
 	<td>
  		<?php echo $value['cus_telnumber'] ?>
  	</td>
  	  	<td>
 	 <?php echo $value['cus_email'] ?>
  	</td>
 	<td>
  		<?php echo $value['cus_time'] ?>
  	</td>
  	  	<td>
 	 <?php echo $value['cus_integral'] ?>
  	</td>

  </tr>
  <?php } ?>			 	
  		
</table>
</center>
</body>
</html>
您可以修改您的个人信息，<a href="<?php echo $this->baseUrl() . '/Customer/customerinformationalter'?>">现在就修改？</a><br />
您还可以发表评论，<a href="<?php echo $this->baseUrl() . '/Membership/customercomment'?>">现在马上评论？</a><br />

