<link href="<?php
echo $this->baseUrl() . '/skin/css/ZYFcustomer.css'?>"
	media="screen" rel="stylesheet" type="text/css" />
<!-- 左面板 start -->
<div class="left">
<div class="subdiv">
<p class="top">&nbsp;</p>
<h2>会员管理</h2>
<div class="reme"><br>
<img src="<?php
echo $this->baseUrl() . '/skin/image/ZYFcomments.png'?>" /> <a href="#">会员评论</a><br>
<br>
<img
	src="<?php
echo $this->baseUrl() . '/skin/image/ZYFuser_comment.png'?>" /> <a
	href="#">会员信息</a></div>
<p class="bot"></p>
</div>

<div class="subdiv">
<p class="top">&nbsp;</p>
<h2 class="event">订票业务</h2>
<div class="reme"><br>
<img src="<?php
echo $this->baseUrl() . '/skin/image/ZYFmagnifier.png'?>" /> <a href="#">航班查询</a><br>
<br>
<img src="<?php
echo $this->baseUrl() . '/skin/image/ZYFmonitor_add.png'?>" /> <a href="#">会员订票</a><br>
<br>
<img src="<?php
echo $this->baseUrl() . '/skin/image/ZYFmonitor_delete.png'?>" /> <a href="#">会员退票</a><br>
<br>
<img src="<?php
echo $this->baseUrl() . '/skin/image/ZYFpage_copy.png'?>" /> <a href="#">会员订单</a><br>
<br>
</div>
<p class="bot">&nbsp;</p>
</div>
</div>
<!-- 左面板 end -->

<!-- 右面板 start -->

<div class="right">
<div class="left-top-corner">
<div class="right-top-corner">
<div class="border-top"></div>
</div>
</div>
<div class="border-left">
<div class="border-right">
<div class="inner">
<iframe style="width: 100%;height:420px;border:none;">

</iframe>
</div>

</div>
</div>
<div class="left-bot-corner">
<div class="right-bot-corner">
<div class="border-bot"></div>
</div>
</div>
</div>

<!-- 右面板 end -->