<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<title>退票信息</title>
<script type="text/javascript"
	src="<?php
echo $this->baseUrl() . '/skin/source/jquery/jquery.js';
?>"></script>
<script type="text/javascript">
$(document).ready(function(){
	$("#s").click(function(){
		var boo_autoid=$("#boo_autoid").text();
		//alert(data);
		$.ajax({
			type:"post",
			url:"/Airline/Customer/refundtickethandler",
			contentType: "application/x-www-form-urlencoded; charset=utf-8",
			cache: true,
			data:{boo_autoid:boo_autoid},
			success:function(data,textStatus){
				//alert("success");
				//window.location.href="/Airline/Customer/bookhistory";
			},
			error: function(data, textStatus) { }
		});
	});
});

</script>

</head>
<body>
<div>
<fieldset style="width:96%;">
	<legend>机票信息</legend>
    <table width="564" height="147" border="0" align="center" cellpadding="0" cellspacing="0">
    <?php foreach ($this->refundticket as $key => $value) {	?>
    
    <tr>
		<td width="20%">&nbsp;航&nbsp;班&nbsp;号:</td>
        <td width="40%"><?php echo $value['com_code'].$value['boo_no'] ?></td>
        <td width="20%">&nbsp;</td>
        <td width="20%">座&nbsp;位&nbsp;号:</td>
        <td width="40%"><?php echo $value['boo_number']?></td>
     </tr>
    
     <tr>
     	
		<td colspan="1"></td>
        <td><?php echo $value['boo_baddress']?></td>
        
        <td>--------</td>
        <td><?php echo $value['boo_aaddress']?></td>
      </tr>
      <tr>
        <td colspan="1"></td>
        <td><?php echo "(".$value['boo_btime'].")"?></td>

        <td></td>
        <td><?php echo "(".$value['boo_atime'].")"?></td>
        <td></td>
        
        
      </tr>
	<tr>
        <td>飞行日期:</td>
        <td><?php echo $value['boo_everyday']?></td>
        <td></td>
        <td>票&nbsp;&nbsp;&nbsp;&nbsp;价:</td>
        <td><?php echo $value['boo_fare']?></td>
      </tr>
      <tr>
        <td>订票时间:</td>
        <td><?php echo $value['boo_time']?></td>
        <td>&nbsp;</td>
       
        <td id="s"><a href="#">确认退票</a></td>
        <td><a href="<?php echo $this->baseUrl()?>/Customer/bookhistory">返    回</a></td>
        <!--<td><input type="button" value="返   回" id="back" /></td>
         <td><input type="button" value="确认退票" id="s" /></td>
        
        <td></td>-->
      </tr>
    </table>
    <div>
   		<table>
   			<tr>
   				<td id="boo_autoid" style="display:none"><?php echo $value['boo_autoid']?></td>
   			</tr>
   		</table>
    </div>
    <?php }?>
</fieldset>
</div>
</body>
</html>