
<link href="<?php
echo $this->baseUrl() . '/skin/css/ZJPaboutus.css'?>"
	rel="stylesheet" type="text/css" />

<table cellspacing="0" cellpadding="0">

	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>

		<td>
		<center>
		<p><img src="skin/image/ZJP01.jpg" alt="曾少宁老师" width="162"
			height="145" /></p>
		<p>曾少宁</p>
		</center>
		</td>
		<td>
		<p>职位：教师</p>
		<p>学习经历：(2000~2004~2007) 北京航空航天大学， 宇航学院， 软件学院</p>
		<p>研究方向与研究兴趣：</p>
		<p>1. 软件工程：面向对象软件工程，软件工程建模与UML，敏捷软件开发过程；</p>
		<p>2. 互联网应用及Web技术：信息安全与管理系统，知识库专家系统，移动信息化技术，Web与移动教育信息化，电子商务与在线支付，Web
		2.0技术</p>
		<p>3. 数据库：通用数据库系统及数据库理论，分布式数据库，XML数据库，面向对象数据库；</p>
		<p>4. Linux与开放源码研究：Linux服务器与桌面应用，Linux云计算，开源社区，开源项目，开源教育</p>
		<p>教学网站：<a href="http：//zsn.cc/" target="_blank" style="">http：//zsn.cc/</a></p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">

	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP07.png" alt="叶茂安" width="162" height="145" /></p>
		<p>叶茂安</p>
		</center>
		</td>
		<td>
		<p>职位：组长</p>
		<p>班级：08软件二班</p>
		<p>学号：081403229</p>
		<p>联系方式：summerdir@gmail.com</p>
		<p>感兴趣的技术：java、struts2、hibernate、spring、extjs、jsp</p>
		<p>系统完成部分：系统划分，订票，退票，航班查询，项目管理</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP05.jpg" alt="杨海亮" width="162" height="145" /></p>
		<p>杨海亮</p>
		</center>
		</td>
		<td>
		<p>职位：分組长<p>
		<p>班级：08软件二班</p>
		<p>学号：081403227</p>
		<p>联系方式：675679978@qq.com</p>
		<p>感兴趣的技术：extjs、struts、hibernate、spring 、java、php、asp.net、javaScript、
		jsp</p>
		<p>系统完成部分：通告，外观设计</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP03.png" alt="李照意" width="162" height="145" /></p>
		<p>李招意</p>
		</center>
		</td>
		<td>
		<p>职位：分组长<p>
		<p>班级：08软件二班</p>
		<p>学号：081403212</p>
		<p>联系方式：839697835@qq.com</p>
		<p>感兴趣的技术：java、extjs、mysql、html、css、javascript、hibernate、spring、vb、c++</p>
		<p>系统完成部分：会员评论，会员登录，会员信息</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP04.jpg" alt="张健平" width="162" height="145" /></p>
		<p>张健平</p>
		</center>
		</td>
		<td>
		<p>职位：组员<p>
		<p>班级：08软件二班</p>
		<p>学号：081403230</p>
		<p>联系方式：997622639@qq.com</p>
		<p>感兴趣的技术：extjs、jsp、asp.net、php、html、css、vb、java、c++</p>
		<p>系统完成部分：客服，系统关于，天气信息查询，航班订票系统折线图</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP09.jpg" alt="叶景" width="162" height="145" /></p>
		<p>叶景</p>
		</center>
		</td>
		<td>
		<p>职位：组员<p>
		<p>班级：08软件二班</p>
		<p>学号：081403228</p>
		<p>联系方式：103493179@qq.com</p>
		<p>感兴趣的技术：html 、struts、hibernate、spring 、java、php、android、 jsp</p>
		<p>系统完成部分：酒店信息，航班优惠</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP08.jpg" alt="庄秋乃" width="162" height="145" /></p>
		<p>庄秋乃</p>
		</center>
		</td>
		<td>
		<p>职位：组员<p>
		<p>班级：08软件二班</p>
		<p>学号：081403238</p>
		<p>联系方式：928406931@qq.com</p>
		<p>感兴趣的技术：html 、struts、hibernate、spring 、java、php、android、 jsp</p>
		<p>系统完成部分：会员注册，会员信息维护，航空公司信息</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP02.jpg" alt="周永丰" width="162" height="145" /></p>
		<p>周永丰</p>
		</center>
		</td>
		<td>
		<p>职位：组员<p>
		<p>班级：08软件二班</p>
		<p>学号：081403236</p>
		<p>联系方式：965141813@qq.com</p>
		<p>感兴趣的技术：ExtJs,Jquery、Ext Core、JavaScript、Java、PHP、C++、VB、C#、Ruby</p>
		<p>系统完成部分：会员订单、航班查询</p>
		</td>
	</tr>
</table>
<table cellspacing="0" cellpadding="0">
	<tr>
		<th width="20%">个人介绍</th>
		<th>详细资料</th>
	</tr>
	<tr>
		<td>
		<center>
		<p><img src="skin/image/ZJP06.jpg" alt="卢伟灵" width="162" height="145" /></p>
		<p>卢伟灵</p>
		</center>
		</td>
		<td>
		<p>职位：特别嘉宾<p>
		<p>班级：08软件二班</p>
		<p>学号：081403218</p>
		<p>联系方式：weiling103@163.com</p>
		<p>感兴趣的技术：vb,C,C++,C#,java,phython,asp.net,Andriod,Linux</p>
		<p>系统完成部分：会员订单、航班查询</p>
		</td>
	</tr>
</table>