<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="skin/css/ZJPaboutus.css" rel="stylesheet" type="text/css" />

<div>
<table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
  <br />
   <br />
    <br />
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:10px' >
	    <p><a name="指导老师">指导老师--曾少宁老师</a></p>
	    
        <p><img src="skin/image/ZJP01.jpg" alt="曾少宁老师" width="162" height="145" /></p>       
     <p><a href="http://zsn.cc/" target="_blank">曾少宁老师教学网站http://zsn.cc/</a></p>
        <p>学习经历 (2000~2004~2007) 北京航空航天大学， 宇航学院， 软件学院</p>
        <p> 研究方向与研究兴趣：</p>
        <p>1. 软件工程：面向对象软件工程，软件工程建模与UML，敏捷软件开发过程；</p>
        <p>2. 互联网应用及Web技术：信息安全与管理系统，知识库专家系统，移动信息化技术，Web与移动教育信息化，电子商务与在线支付，Web 2.0技术</p>
        <p>3. 数据库：通用数据库系统及数据库理论，分布式数据库，XML数据库，面向对象数据库；</p>
        <p>4. Linux与开放源码研究：Linux服务器与桌面应用，Linux云计算，开源社区，开源项目，开源教育</p>    
       </td>
  </tr>
 </table>
<table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:50px' >
	    <p><a name="组长"> 组长</a></p>
        <p><img src="skin/image/ZJP07.png" alt="叶茂安" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403229   姓名：叶茂安  联系方式:summerdir@gmail.com</p>
        <p>感兴趣的技术:java、struts2、hibernate、spring、extjs、jsp</p>
        <p> 系统完成部分：系统划分，订票，退票，航班查询，项目管理</p>
       </td>
  </tr>
 </table>
 <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:100px' >
	    <p><a name="分组长"> 分组长</a></p>
        <p><img src="skin/image/ZJP05.jpg" alt="杨海亮" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403227   姓名：杨海亮  联系方式：675679978@qq.com</p>
        <p>感兴趣的技术：extjs、struts、hibernate、spring 、java、php、asp.net、javaScript、 jsp</p>
        <p> 系统完成部分：通告，外观设计</p>
       </td>
  </tr>
 </table>
<table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:150px' >
	    <p><a name="成员介绍1"> 小组成员</a></p>
        <p><img src="skin/image/ZJP04.jpg" alt="张健平" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403230   姓名：张健平  联系方式：997622639@qq.com</p>
        <p>感兴趣的技术：extjs、jsp、asp.net、php、html、css、vb、java、c++</p>
        <p> 系统完成部分：客服，系统关于，天气信息查询，航班订票系统折线图</p>
       </td>
  </tr>
 </table>
 <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:150px' >
	    <p><a name="成员介绍2"> 小组成员</a></p>
        <p><img src="skin/image/ZJP09.jpg" alt="叶景" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403228   姓名：叶景  联系方式：103493179@qq.com</p>
        <p>感兴趣的技术：html 、struts、hibernate、spring 、java、php、android、 jsp</p>
        <p> 系统完成部分：酒店信息，航班优惠</p>
       </td>
  </tr>
 </table>
 <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:100px' >
	    <p><a name="分组长"> 分组长</a></p>
        <p><img src="skin/image/ZJP03.png" alt="李照意" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403212   姓名：李照意  联系方式：1139482934@qq.com</p>
        <p>感兴趣的技术：java、extjs、mysql、html、css、javascript、hibernate、spring、vb、c++</p>
        <p> 系统完成部分：会员评论，会员登录</p>
       </td>
  </tr>
 </table>
 <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:150px' >
	    <p><a name="成员介绍3"> 小组成员</a></p>
        <p><img src="skin/image/ZJP08.jpg" alt="庄秋乃" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403238   姓名：庄秋乃  联系方式： 928406931@qq.com</p>
        <p>感兴趣的技术：html 、struts、hibernate、spring 、java、php、android、 jsp</p>
        <p> 系统完成部分：会员注册，会员信息维护，航空公司信息</p>
       </td>
  </tr>
 </table>
 <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:150px' >
	    <p><a name="成员介绍4"> 小组成员</a></p>
        <p><img src="skin/image/ZJP02.jpg" alt="周永丰" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403236   姓名：周永丰  联系方式： 965141813@qq.com</p>
        <p>感兴趣的技术:ExtJs,Jquery、Ext Core、JavaScript、Java、PHP、C++、VB、C#、Ruby</p>
        <p> 系统完成部分：订票，退票，航班查询</p>
       </td>
  </tr>
 </table>
  <table width=100% border=0 cellpadding=0 cellspacing=0>	
  <tr height=30 >
    <td width=100% style='font:bold 16px Tahoma,Verdana;padding-left:50px' >
	    <p><a name="特别感谢"> 特别感谢</a></p>
        <p><img src="skin/image/ZJP06.jpg" alt="卢伟灵" width="162" height="145" /></p>
        <p> 班级学号:08软件二班081403218   姓名：卢伟灵  联系方式： weiling103@163.com</p>
        <p>感兴趣的技术:vb,C,C++,C#,java,phython,asp.net,Andriod,Linux</p>
        <br></br>
        <br></br>
        <br></br>
       </td>
  </tr>
 </table>
</div>