<div id="footerbig">
          <div id="footer">
            <ul>
              <li><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'));?>">首页</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Hotelinformation','action'=>'index'));?>"> 酒店信息</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Flightcompany','action'=>'index'));?>">航空公司信息</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Bookinformation','action'=>'index'));?>">航班预定查询</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Customer','action'=>'index'));?>">航程会员</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Customerservice','action'=>'index'));?>">客户服务</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Sitehelp','action'=>'index'));?>">网站帮助</a></li>
                    <li>|</li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Aboutus','action'=>'index'));?>">关于我们</a></li>
            </ul>
                 <p>Copyrioht &copy; Eco Mania 2007 All Rights Reserved</p>
				 <p>Powered by <a target="_blank" href="http://templatekingdom.com">TemplateKingdom.com</a></p>
          </div>
    </div>