<div id="footerbig">
          <div id="footer">
            <ul>
              <li><a href="Index">首页</a></li>
                    <li>|</li>
                    <li><a href="Hotelinformation"> 酒店信息</a></li>
                    <li>|</li>
                    <li><a href="Flightcompany">航空公司信息</a></li>
                    <li>|</li>
                    <li><a href="Bookinformation">航班预定查询</a></li>
                    <li>|</li>
                    <li><a href="Customer">航程会员</a></li>
                    <li>|</li>
                    <li><a href="Customerservice">客户服务</a></li>
                    <li>|</li>
                    <li><a href="Sitehelp">网站帮助</a></li>
                    <li>|</li>
                    <li><a href="Aboutus">关于我们</a></li>
            </ul>
                 <p>Copyrioht &copy; Eco Mania 2007 All Rights Reserved</p>
				 <p>Powered by <a target="_blank" href="http://templatekingdom.com">TemplateKingdom.com</a></p>
          </div>
    </div>