<!-- 编辑者：李招意 -->
<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>发表评论</title>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/skin/source/jquery/jquery.js' ;?>"></script>
<body>
<script type="text/javascript">
	$(document).ready(function(){
		$("#submit").click(function(){
			//var comment_content=$("#comment_content").val();
			if ($.trim($("#comment_content")[0].value) == "")
			{
			  alert("评论内容不能为空！");
			}else{
			  alert("发表成功");
			}
			//获取后台传来的success进行判断
			
		});

	});	
</script>
<a style="float:right" href="<?php echo $this->baseUrl() . '/Customer/customerlogout'?>">退出系统</a><br />
<form action="customercomment" method="post">
<div id="commentform" style="background:#FFFFF;">
<h5><?php Zend_Session::start(); 
  $customerNamespace = new Zend_Session_Namespace('customer');
   $login_or_not=$customerNamespace->login_or_not;
  if($login_or_not===true){
  echo $customerNamespace->cus_account;?>您好,请在下面的输入框中发表您的评论
</h5>
<textarea name="comment_content" id="comment_content" cols="70" rows="5"></textarea>
  <p align="left"><!--
  账号：<input type="text" size="12" name="cus_account" id="cus_account" />
  密码：<input type="text" size="12" name="cus_pwd" id="cus_pwd" />
  新会员？<a href="http://localhost/Airline/Customer/register">会员注册</a>
  -->
  <input type="submit" id="submit" name="sent" value="发表评论" >
  <input type="reset" name="reset" value="取消评论" >
  </p>
</div>
</form>
<a href="<?php echo $this->baseUrl() . '/Customer/customerinfomationshow'?>">返回会员个人信息页面</a>
<?php 
  } else {
  		$src= $this->baseUrl() . '/Customer/customerlogout';
	    echo "您还没有登录，必须要在登录后才能评论";
	    echo "&nbsp;&nbsp;";
	    echo "<a href='$src'>请点击我现在登录</a>";
  }
?>
<body>
</body>
</html>