<!-- 编辑者：李招意 -->
<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<form action="customercomment" method="post">
<div id="commentform">
我也来评论 <br />
<textarea name="comment_content" cols="65" rows="4"></textarea>
  <p align="left">
  账号：<input type="text" size="12" name="cus_account" id="cus_account" />
  密码：<input type="text" size="12" name="cus_pwd" id="cus_pwd" />
  新会员？<a href="http://localhost/Airline/Customer/register">会员注册</a>
  <input type="submit" name="sent" value="发表评论" >
  </p>
</div>
</form>
<table width="700" height="160" border="6" bordercolor="00CCFF">
  <tr>
    <th>会员账号</th>
    <th>评论内容</th>
  </tr>
  <?php 
  		foreach($this->membership as $key=>$value){
  ?>
  <tr>
  	<td>
 	 <?php echo $value['customer_name'] ?>:
  	</td>
 	 <td>
  		<?php echo $value['comment_content'] ?>
  	</td>
  	<td>
  		<a href="http://localhost/Airline/Membership/comment">回复此评论</a>
  	</td>
  </tr>
  <?php } ?>			
</table>

